root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main ."
  bin = "tmp/main"
  include_ext = ["go", "env"]
  exclude_dir = ["tmp", "docs"]
  delay = 100  # Delay in milliseconds before restart

[log]
  time = true
